# Generated by Django 2.2.10 on 2021-01-30 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politico', '0002_auto_20210130_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='amendement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='politico.Amendement'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='seance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='politico.Seance'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='total_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politico.TotalVote'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='politico.Voter'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voting_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='politico.VotingPoint'),
        ),
    ]
