# Generated by Django 2.2.10 on 2021-01-30 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politico', '0003_auto_20210130_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendement',
            name='voting_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politico.VotingPoint'),
        ),
    ]
